spring:
  application:
    name: eventclean

    datasource:
        url: jdbc:postgresql://localhost:5431/eventclean
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
      show-sql: true

      flyway:
        enable: true




