server:
  port: 8081

spring:
  application:
    name: eventClean

  datasource:
    url: jdbc:postgresql://localhost:5431/eventclean
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration





